### ISSUE TITLE
Hackathon Card

### ISSUE THREAD

**Issue by m-e-l-u-h-a-n** [COPS-IITBHU/hackalog-frontend#11]
A better hackathon card component is needed to display a hackthon in a shorter format.

**Comment by pathakshashank17** [comment]
Is this issue still open? The cards at [Google Kick Start](https://codingcompetitions.withgoogle.com/kickstart/archive) or [Gogle Hash Code](https://codingcompetitions.withgoogle.com/hashcode/archive) look good and minimalistic.

**Comment by m-e-l-u-h-a-n** [comment]
@pathakshashank17 Yupp, but we needed some more info to put in the card.. You can see the required info to be included in the home page which is already created.

**Comment by shubhanshu02** [comment]
Closed by #13
