### ISSUE TITLE
Contributors Page: Possible Recursive Loop in useEffect

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#121]
### Description

Have a look at the following code snippet from `pages/contributors.tsx`:

https://github.com/COPS-IITBHU/hackalog-frontend/blob/2ea02ec0d45624872dd23207273f9bccdb52aef2/pages/contributors.tsx#L107-L123

### Problem

It shows an ESLint warning as follows:
 
> React Hook useEffect has a missing dependency: 'fullname'. Either include it or remove the dependency array. You can also do a functional update 'setFullName(f => ...)' if you only need 'fullname' in the 'setFullName' call. eslintreact-hooks/exhaustive-deps

If we correct this problem by adding the `fullname` dependency to the `useEffect` hook, we get stuck in a never-ending loop since the hook will be triggered by a change in `fullname` where this hook is again changing the `fullName`. 

### Possible Solutions

1. Ignore the warning and add a comment there to avoid fixing the dependencies in the future.
2. Refactor the code to avoid this extra hook - Instead of using a separate `useEffect` hook for this purpose, we can transfer the code to the same hook which sets the `contributors`.

**Comment by tiger-yash** [comment]
I had initially used the `contributors` hook only for this purpose but then it shows more errors as axios do not update the arrays immediately, and the dependencies don't let that from happening.

**Comment by shubhanshu02** [comment]
Why are we storing the same data in many places, anyway :thinking:? Can't we have a single data structure to store all contributors?

**Comment by tiger-yash** [comment]
No, single data structure won't do since the data from both API have few common people and then after sorting that, we need to fetch and store the Full Names separately.

**Comment by shubhanshu02** [comment]
No problem, then. We'll deal with it later.
