### ISSUE TITLE
no changes while hovering in navbar

### ISSUE THREAD

**Issue by pratham1103** [COPS-IITBHU/hackalog-frontend#129]
while hovering over the buttons on navbar there is no changes in color or details, so i would like to add some finer details to it to make it more appealing

**Comment by pratham1103** [comment]
I just wanted to know that is there any html sheet also, just so I can check the changes personally before submitting?

**Comment by pratham1103** [comment]
yes yes, actually I am not getting the sheet which I can run on my browser to check the changes,
I am working on VSCode, so I need some HTML sheet to Go Live and check the changes?

**Comment by shubhanshu02** [comment]
Got your point. Actually, everything in this project is written in React. You can find the header in `components/Header/Header.tsx`. 

To go live and check the changes, have a look at the steps in the [README.md](https://github.com/COPS-IITBHU/hackalog-frontend/blob/main/README.md).

**Comment by pratham1103** [comment]
yes i am working on this
