### ISSUE TITLE
Damaged Footer 

### ISSUE THREAD

**Issue by Shubhrajyoti-Dey-FrosTiK** [COPS-IITBHU/hackalog-frontend#147]
In the production as per the given link https://hackalog.copsiitbhu.co.in/ the footer section is broken as shown in the pics below

<img width="1792" alt="Screenshot 2021-10-13 at 1 36 31 AM" src="https://user-images.githubusercontent.com/75834423/137021901-bc2204d8-11f6-402d-9629-f9915449a0b5.png">

Moreover the mobile view is also not responsive as per the production website

I want to fix this. Can I please get the chance to do so ?

**Comment by shubhanshu02** [comment]
As @Hitansh-Shah mentioned, this issue doesn't seem to be only with the footer. In my case, the text and font was distorted on the entire page :thinking:
