### ISSUE TITLE
Github handles are converted to lowercase

### ISSUE THREAD

**Issue by Hitansh-Shah** [COPS-IITBHU/hackalog-frontend#150]
The github handle provided by user are displayed in lowercase in user profile. Though "https://github.com/username" will take to correct github profile even by randomly changing the case of any letter in the username string, I guess it will be more appropriate if we show the exact github username provided by user.

**Comment by shubhanshu02** [comment]
Hi, @Hitansh-Shah! Sorry I didn't get what you are trying to say. Can you elaborate or give an example?
