### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ashwat287** [COPS-IITBHU/hackalog-frontend#161]
<img width="1040" alt="Screenshot 2021-10-21 at 08 32 43" src="https://user-images.githubusercontent.com/85362194/138423445-4404aa65-b3ff-4355-bd5c-6b92b6ddec0c.png">

<img width="660" alt="Screenshot 2021-10-22 at 14 17 10" src="https://user-images.githubusercontent.com/85362194/138423759-857d6dc7-0b20-400c-9d1e-601891e2b7cb.png">

**Comment by NerdyLucifer** [comment]
The issue got fixed, this time i used yarn instead of using npm and no error popped
Everything running fine!
