### ISSUE TITLE
Submission Detail Page showing wrong Start and End dates for hackathon

### ISSUE THREAD

**Issue by shubham1710** [COPS-IITBHU/hackalog-frontend#62]
In the submission details page for any submission, in the last part, where Hackathon Details are shown, the start and the end date is showing as the current date and time but it should display the time when the hackathon started and ended so it is wrongly displayed there. 

The same start and end date is correctly displayed on Hackathon detail page but is wrong on any submissions detail page.
![Screenshot_20210221-092513_Chrome](https://user-images.githubusercontent.com/27803267/108615198-8773ec80-7427-11eb-8344-c2c76d446ca8.jpg)

**Comment by subodhk01** [comment]
@shubham1710 Do you want to work on this issue?

**Comment by shubham1710** [comment]
Sure! I will try to fix it.

**Comment by shubhanshu02** [comment]
@shubham1710, here are some points that'll help in solving this issue.

1. The code for this page can be found in `pages/submission/[id].js`.
2. The hackathon's start and end time is received from the back end in the ISO format like `2021-02-12T12:00:00Z`.
3. We need to display these dates in a readable form.

## Probable Solutions
1. You may use some javascript functions to parse the ISO format.
2. A better and simpler solution will be to use some package like `Moment.js` and display the date in a readable format.
```js
moment().format('llll'); // Sun, 21 Feb 2021 12:56 PM
moment().format('LLLL'); // Sunday, 21 February 2021 12:56 PM
```
Feel free to ask if you need any help.

**Comment by shubham1710** [comment]
I have opened a pull request which fixes the issue. Thanks for these suggestions and information.
