### ISSUE TITLE
Invalid Thumbnail link for DebugIt

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#64]
### Bug 
The card for DebugIt is not showing any image. This points that the thumbnail link is now invalid.

### Details
Page: https://hackalog.copsiitbhu.co.in/hackathons
Browser: Chrome 90. (though bug visible on other browsers as well)

**Comment by shubhanshu02** [comment]
**Update**: Replace the old link by [this](https://cdn.discordapp.com/attachments/775731419837890570/844295973496291328/debugit.jpeg) link to fix the bug.

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by shubhanshu02** [comment]
> Can I work on this issue?

Sure

**Comment by ujju20** [comment]
I am unable to find DebugIt in hackathons.js file

**Comment by king-11** [comment]
I guess this is a database entry issue @shubhanshu02 🤔 we might have used a google link or something

**Comment by shubhanshu02** [comment]
Lemme check where the link really is.

**Comment by shubhanshu02** [comment]
Ya, right, @king-11. It was an issue on the database side. I've updated the link in the database, and the issue seems to be fixed now. The old link shows `Access Denied` btw.
@ujju20, you may try some other issues for now.

**Comment by ujju20** [comment]
> Ya, right, @king-11. It was an issue on the database side. I've updated the link in the database, and the issue seems to be fixed now. The old link shows `Access Denied` btw.
> @ujju20, you may try some other issues for now.

OK
