### ISSUE TITLE
External Anchor should include 'noopener' as rel attribute

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#65]
### Details

According to [this](https://webhint.io/docs/user-guide/hints/hint-disown-opener/), anchor tags containing external links with `target="_blank"` and the link is external to the origin. This helps prevent malicious attacks and reduce page jank in Chromium browsers.

### Occurrences

- `pages/submission/[id].js`
- `pages/profile/[username].js`
- `components/Footer/Footer.js`

### Fix Steps

Add `rel="noopener noreferrer"` as an attribute to the anchor tags in each such occurrence.

**Comment by ujju20** [comment]
I am taking up this issue.

**Comment by ujju20** [comment]
I have sent a PR for this issue please check.
