### ISSUE TITLE
Contributors Page

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#72]
### Description

A page to display a list of all contributors to the repository, directly fetched from the GitHub API.

**Comment by tiger-yash** [comment]
I am taking up this issue, could u please share some more details?

**Comment by subodhk01** [comment]
- You have to dynamically fetch the contributor's list from this and the backend repo `hackalog-backend` and display it on a separate page.
- Initially you can place the link in footer
- Yeah for now you can create a profile card on your own, but remember to follow the UI design and keep the css minimal.

**Comment by shubhanshu02** [comment]
I agree with @subodhk01. Just a few things to add.

- For fetching the contributors' list, you can have a look at [this](https://docs.github.com/en/rest/reference/repos#list-repository-contributors).
- I guess `/contributors` would be good for the pathname of the page.
- The list for the backend and frontend contributors would contain some common contributors. You can include the repo the user has contributed to (backend/frontend or both) in the card.

**Comment by tiger-yash** [comment]
In the Card should will i have to mention the name of the Person(which will require to GET the Name of each contributor separated via API) or is the github username fine?

**Comment by subodhk01** [comment]
Considering that you have to make separate calls for Full Names, just usernames are fine for now
