### ISSUE TITLE
Font-sizes of Footer and Sub-Header rescaling on deployment

### ISSUE THREAD

**Issue by tiger-yash** [COPS-IITBHU/hackalog-frontend#85]
On deployment the Size of Text in the common Element below the Header and the Footer are taking time to load correctly which resolves automatically after reloading the site from a page other than Home Page. Problem not present in local version.

**Comment by tiger-yash** [comment]
The might be resolved simply by Re-Deploying the Website, as During my commits I face similar issue once in the preview and it automatically resolved when I just made a dummy commit again to re-initiate the preview.

**Comment by shubhanshu02** [comment]
Ya right I also noticed this problem now. Let me check where the problem is.
