### ISSUE TITLE
Rename 'Projects' tab to 'Teams' in Profile Page

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#89]
Currently, the 'Projects' tab on the profile page shows the teams the user is a part of, regardless of whether the team actually submitted a project or not. So, the name 'Projects' is a bit confusing since it doesn't serve the purpose.

### Task

- Rename 'Projects' tab to 'Teams' in Profile Page

**Comment by PuneetDabral** [comment]
may i contribute ......??

**Comment by shubhanshu02** [comment]
Yeah, sure!

**Comment by PuneetDabral** [comment]
sir i am new in open source can you please help me ..for my first contribution so i am motivated...

**Comment by shubhanshu02** [comment]
Here are some points you may need.

- You'll first need to set up the repository (See [readme](README.md)).
- The file `/pages/profile/[username.js]` corresponds to the Profile page. In the source code of this file, there's a `Nav` component from react-bootstrap. You need to do changes here as mentioned above in the issue description.
- Then, run the dev server and verify the changes you have done.
- Follow contribution guidelines written [here](CONTRIBUTING.md).

**Comment by PuneetDabral** [comment]
ok sir i will try ....!!

**Comment by PuneetDabral** [comment]
@shubhanshu02 sir i have made a branch with my name what i can do next...?actually i am little bit confuse because it is my first time ..

**Comment by PuneetDabral** [comment]
ok sir i am creating a pull request please review it and give me a chance to contribute (so i can see my name in contributor list) @shubhanshu02 thanks you for your guidance ....(and give me a chance in future also)..
