### ISSUE TITLE
Profile Page Edit Modal: Add validation to text fields.

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#90]
Currently, in the edit profile modal on the Profile page,  the usernames such as “ABC DEF” are allowed while trimming is done only on either end. Due to this, the URLs are changed to something like `https://hackalog.copsiitbhu.co.in/profile/ABC%20DEF`.

Though everything works fine, this should be avoided when possible.

### Tasks

- [ ] Add validation to the username field
- [ ] Add validation to GitHub username field.

### Possible Solutions

1. Show an invalid username warning.
2. Trim all the whitespaces in the middle of such fields before sending them to the backend

**Comment by somesh202** [comment]
@shubhanshu02  Can I work on this issue?

**Comment by shubhanshu02** [comment]
Sure!
